### ISSUE TITLE
In DC-iOS it is not possible to access a bot via app

### ISSUE THREAD

**Issue by Raiden-GH** [deltachat-bot/public-bots#4]
In DC-iOS 1.42.8 it is not possible to call a bot via the bot app. 
The chat cannot be opened even by tapping the link several times. Nothing happens. 
The problem does not exist in DC-Desktop and DC-Android.

**Comment by adbenitez** [comment]
hi, sorry for the late reply, the problem is that DC in iOS doesn't support opening the kind of link that is used for contact verification in DC

**Comment by adbenitez** [comment]
recent DC iOS version already support the bot links (fixed in https://github.com/deltachat/deltachat-ios/pull/2158)
